---
title: "lincs_adapted_bin_chen"
author: "Lauren Cech"
date: "2/3/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#Library
```{r}
library(qvalue)
library(Seurat)
library(sctransform)
library(ggplot2)
library(tidyverse)
library(gridExtra)
library(devtools)
library(ggsignif)
library(ggpubr)
library(plotly)
library(ggridges)
library(tibble)
library(reshape)
library(gridExtra)
library(ggrepel)
library(ggExtra)
library(readxl)
library(RColorBrewer)
library(rstatix)
library(extrafont)
library(patchwork)
#fonts() 
#loadfonts()
library(scales)
library(dplyr)
library(reshape2)
custom_theme <- theme(
  plot.title = element_text(size=20, hjust = 0.5), 
  legend.key.size = unit(0.7, "cm"), 
  legend.text = element_text(size = 18))
```
#prepare signatures for lincs
```{r}

#original workflow at https://github.com/Bin-Chen-Lab/HCC_NEN/blob/master/drug_prediction/build_dz_signature.R)
#general workflow for single cell disease signature with this dataset
cancer <- "LUAD"
load("/LOCATION/OF/DIFFENTIAL/EXPRESSION/DATA.RData")
#Label Updates
tiss_subset@meta.data$treatmentadjust <- tiss_subset@meta.data$treatment
tiss_subset@meta.data <- tiss_subset@meta.data %>% mutate(treatmentadjust =
                     case_when(treatment == "alectinib" ~ "Alectinib [ALKi]", 
                               treatment == "erlotinib" ~ "Erlotinib [EGFRi]",
                               treatment == "ceritinib/trametinib" ~ "Combinatorial",
                               treatment == "erlotinib/gemcitabine" ~ "Combinatorial",
                               treatment == "dabrafenib/trametinib" ~ "Combinatorial",
                               treatment == "None" ~ "None",
                               treatment == "osimertinib" ~ "Osimertinib [EGFRi]",
                               treatment == "crizotinib" ~ "Crizotinib [ALKi; ROS1i]",
                               treatment == "followed elsewhere" ~ "Left Treatment",
                               treatment == "radiation" ~ "Radiation",
                               treatment == "lorlatinib" ~ "Lorlatinib [ALKi; ROS1i]",
                               treatment == "trametinib" ~ "Trametinib [MEKi]"))

tiss_subset@meta.data <- tiss_subset@meta.data %>% mutate(ClinicalTimepoint =
                     case_when(analysis == "naive" ~ "Treatment Naive", 
                               analysis == "grouped_pr" ~ "Residual Disease",
                               analysis == "grouped_pd" ~ "Acquired Resistance"))

tiss_subset@meta.data <- tiss_subset@meta.data %>% mutate(BiopsySite =
                     case_when(biopsy_site == "Adrenal" ~ "Adrenal", 
                               biopsy_site == "Brain" ~ "Brain",
                               biopsy_site == "Liver" ~ "Liver",
                               biopsy_site == "LN" ~ "Lymph Node",
                               biopsy_site == "lung" ~ "Lung",
                               biopsy_site == "Lung" ~ "Lung",
                               biopsy_site == "Pleura" ~ "Pleura"))

tiss_subset@meta.data <- tiss_subset@meta.data %>% mutate(BiopsyStage =
                     case_when(BiopsySite == "Adrenal" ~ "Metastatic", 
                               BiopsySite == "Brain" ~ "Metastatic",
                               BiopsySite == "Liver" ~ "Metastatic",
                               BiopsySite == "Lymph Node" ~ "Metastatic",
                               BiopsySite == "Lung" ~ "Primary",
                               BiopsySite == "Pleura" ~ "Metastatic")) #need to check for NAs

tiss_subset@meta.data <- tiss_subset@meta.data %>% mutate(CellPopulation =
                     case_when(Final_annotation == "alveolar type 1 cell" ~ "AT1 Cell", 
                               Final_annotation == "alveolar type 2 cell" ~ "AT2 Cell",
                               Final_annotation == "B-cells-M" ~ "Memory B-Cell",
                               Final_annotation == "B-cells-PB" ~ "Plasmablast B-Cell",
                               Final_annotation == "basal cell" ~ "Basal Cell",
                               Final_annotation == "ciliated cell" ~ "Ciliated Cell",
                               Final_annotation == "club cell" ~ "Club Cell",
                               Final_annotation == "Dendritic" ~ "Dendritic Cell",
                               Final_annotation == "endothelial" ~ "Endothelial Cell",
                               Final_annotation == "fibroblast" ~ "Fibroblast",
                               Final_annotation == "hepatocyte" ~ "Hepatocyte",
                               Final_annotation == "Mast-cells" ~ "Mast Cell",
                               Final_annotation == "melanocytes" ~ "Melanocyte",
                               Final_annotation == "MF-Monocytes" ~ "Macrophage-Monocyte",
                               Final_annotation == "neuro.e cell" ~ "Neuroendocrine Cell",
                               Final_annotation == "Neutrophils" ~ "Neutrophil",
                               Final_annotation == "pDCs" ~ "Plasmacytoid Dendritic Cell",
                               Final_annotation == "T-cells" ~ "T-Cell",
                               Final_annotation == "tumor" ~ "Tumor Cell",
                               Final_annotation == "Unknown" ~ "Unknown Cell 1",
                               Final_annotation == "unknown stroma1" ~ "Unknown Stromal Cell 1",
                               Final_annotation == "unknown stroma2" ~ "Unknown Stromal Cell 2",
                               Final_annotation == "unknown stroma3" ~ "Unknown Stromal Cell 3",
                               Final_annotation == "unknown stroma4" ~ "Unknown Stromal Cell 4",
                               Final_annotation == "unknown stroma5" ~ "Unknown Stromal Cell 5",
                               Final_annotation == "ionocyte" ~ "Ionocyte"))

tiss_subset@meta.data <- tiss_subset@meta.data %>% mutate(CellPopulation_State = paste(CellPopulation, ClinicalTimepoint, sep = ' '))
dataUse <- FetchData(tiss_subset, vars = c('cell_id', 'BiopsyStage','ClinicalTimepoint','CellPopulation', 'CellPopulation_State'))
dataUse <- dataUse[complete.cases(dataUse), ]
dataUse <- dataUse[dataUse$CellPopulation == "Tumor Cell", ]
tiss_subset <-SetIdent(tiss_subset,  value = "CellPopulation")
tumor <- subset(x = tiss_subset, idents = "Tumor Cell")

tumor <- UpdateSeuratObject(tumor)
tumor <-SetIdent(tumor,  value = "ClinicalTimepoint") %>%
  FindVariableFeatures(selection.method = "vst", nfeatures = 2000) %>%
  ScaleData()%>%
  RunPCA() %>%
  FindNeighbors() %>%
  FindClusters() %>%
  #ElbowPlot() %>%
  RunUMAP(dims = 1:20) %>%
  RunTSNE(dims = 1:20)
tumor[["tumorSubset.ident"]] <- Idents(tumor)
tumor <-SetIdent(tumor,  value = "ClinicalTimepoint")
allMarkersDefault<-FindAllMarkers(tumor)
dz_signature <- subset(allMarkersDefault, !is.na(p_val_adj) & p_val_adj < 1E-03 & abs(avg_log2FC) > 2 & abs(avg_log2FC) != Inf & cluster == "Residual Disease")
#add NCBI Gene ID AKA ENTREZID
library(AnnotationHub)
# 1. Input 
#dz_signature
# 2. Gene identifier in each row
symbol <- dz_signature$gene

#loadings
ah <- AnnotationHub()
hs <- query(ah, c("OrgDb", "Homo sapiens"))[[1]]
# 3. Corresponding data.frame
symbolToGeneId <- select(hs,
                      column=c("SYMBOL", "ENTREZID"),
                      keytype="SYMBOL", keys=symbol)
names(symbolToGeneId) <- c("gene","GeneID")
#4. bind data.frames
dz_signature.1 <- bind_cols(symbolToGeneId,dz_signature)
dz_signature.1 <- subset(dz_signature.1, select=c("GeneID","gene...9", "avg_log2FC"))
names(dz_signature.1) <- c("GeneID", "Symbol", "value")

dz_signature.1 <- subset(dz_signature.1, !is.na(value))
dz_signature.1 <- dz_signature.1[order(dz_signature.1$value),]
dz_signature.1$up_down <- "up"
dz_signature.1$up_down[dz_signature.1$value < 0] <- "down"
#https://www.synapse.org/#!Synapse:syn6191537 has raw files used for input in original workflow
landmark <- read.csv("./lincs_landmark.csv")
dz_signature.2 <- subset(dz_signature.1, GeneID %in% landmark$gene_id)
```

#predict lincs drugs
```{r}
#few hours computation time
#cmd = paste("Rscript ../code/drug_prediction/predict_drugs_lincs.R", cancer, "lincs", paste(cancer, "/drug/dz_signature_lincs.txt", sep=""), 1)
args <- commandArgs(trailingOnly=T)

subset_comparison_id <- args[1]
analysis_id <-  args[2]
dz_sig_path <- args[3]
landmark <- args[4] #1 means using landmark gene, 0 means using all genes

if (length(args)<4){
  print ("please input 3 arguments (subset comparision id, analysis id, disease signature path, landmark)")
  q()
}

#compute random scores, used for significance analysis
cmd <- paste("Rscript ../code/drug_prediction/compute_cmap_randoms_new_set_lincs_all.R", subset_comparison_id, analysis_id, dz_sig_path, landmark)
system(cmd)
```
#run cmap in lincs
##Compute randoms
```{r}
cmap_score <- function(sig_up, sig_down, drug_signature) {
	
	num_genes <- nrow(drug_signature)
	ks_up <- 0
	ks_down <- 0
	connectivity_score <- 0
	drug_signature[,"rank"] <- rank(drug_signature[,"rank"])

	# Merge the drug signature with the disease signature by GeneID. This becomes the V(j) from the Kolomgorov-Smirnov algorithm description
	up_tags_rank <- merge(drug_signature, sig_up, by.x = "ids", by.y = 1)
	down_tags_rank <- merge(drug_signature, sig_down, by.x = "ids", by.y = 1)

	up_tags_position <- sort(up_tags_rank$rank)
	down_tags_position <- sort(down_tags_rank$rank)

	num_tags_up <- length(up_tags_position)
	num_tags_down <- length(down_tags_position)

	if(num_tags_up > 1 && num_tags_down > 1) {
		a_up <- 0
		b_up <- 0
				
		a_up <- max(sapply(1:num_tags_up,function(j) {
			j/num_tags_up - up_tags_position[j]/num_genes
		}))
		b_up <- max(sapply(1:num_tags_up,function(j) {
			up_tags_position[j]/num_genes - (j-1)/num_tags_up
		}))
		
		if(a_up > b_up) {
			ks_up <- a_up
		} else {
			ks_up <- -b_up
		}

		a_down <- 0
		b_down <- 0

		a_down <- max(sapply(1:num_tags_down,function(j) {
			j/num_tags_down - down_tags_position[j]/num_genes
		}))
		b_down <- max(sapply(1:num_tags_down,function(j) {
			down_tags_position[j]/num_genes - (j-1)/num_tags_down
		}))
		
		if(a_down > b_down) {
			ks_down <- a_down
		} else {
			ks_down <- -b_down
		}
		
		if (sum(sign(c(ks_down,ks_up))) == 0) {
			connectivity_score <- ks_up - ks_down # different signs
		}
	}
	return(connectivity_score)
}

#https://www.synapse.org/#!Synapse:syn6191537 has raw files used for input in original workflow
if (landmark == 1){
  landmark <- read.csv("raw/lincs/lincs_landmark.csv")
  gene.list <- landmark$gene_id
  load("./raw/lincs/lincs_signatures_cmpd_landmark.RData")
  
}else{
  landmark_data <- read.csv("raw/lincs/probe_id_info.csv")
  gene.list <- landmark_data$gene_id
  load("./raw/lincs/lincs_signatures_cmpd_hcc_all.RData")
}
#load for all lincs signatures, but only with landmark genes
load("./raw/lincs/lincs_signatures_cmpd_landmark.RData")
#load for fraction of signatures (relevant to original paper), with all genes
#load("./raw/lincs/lincs_signatures_cmpd_hcc_all.RData")

lincs_sig_info <- read.csv("./raw/lincs/lincs_sig_info.csv")
lincs_sig_info <- subset(lincs_sig_info, id %in% colnames(lincs_signatures))
# 665110 total signatures avail. for comparison
#remove duplicate instances
lincs_sig_info <- lincs_sig_info[!duplicated(lincs_sig_info$id),]
unique(lincs_sig_info$cell_id)
#optional, filter for only lung relevant signatures to reduce computation 
#lung relevant cell lines: lung<-c("A549","HCC15","HCC515","NCIH1694","NCIH2073","NCIH508","NCIH596","SKLU1","H1299")
#lincs_sig_info.1 <- lincs_sig_info[lincs_sig_info$cell_id %in% lung,]

#change col name "is_gold" to "is_exemplar" to match downstream comparison to iLincs
#names(lincs_sig_info) <-c("id", "Signature ID","Perturbagen_ID","Perturbagen","Perturbagen_Description","CellLine","Time","Concentration","Perturbagen_Type","is_exemplar","DrugBank.ID")
#annotate with units post-analyses
sig.ids <- lincs_sig_info$id

# Load in the signature for the subset_comparison_id
dz_genes_up <- subset(dz_signature.2,up_down=="up",select="GeneID")
dz_genes_down <- subset(dz_signature.2,up_down=="down",select="GeneID")

max_gene_size <- 150
#only select 100 genes
if (nrow(dz_genes_up)> max_gene_size){
	dz_genes_up <- data.frame(GeneID=dz_genes_up[1:max_gene_size,])
}
if (nrow(dz_genes_down)> max_gene_size){
	dz_genes_down <- data.frame(GeneID=dz_genes_down[1:max_gene_size,])
}

print ((nrow(dz_genes_up)+nrow(dz_genes_down)))

N_PERMUTATIONS <- 10000 #default 100000
random_sig_ids <- sample(colnames(lincs_signatures),N_PERMUTATIONS,replace=T)
count <- 0
random_cmap_scores <- NULL
for (exp_id in random_sig_ids){
  count <- count + 1
  #print(count)
  cmap_exp_signature <- data.frame(gene.list,  rank(-1 * lincs_signatures[, as.character(exp_id)], ties.method="random"))    
  colnames(cmap_exp_signature) <- c("ids","rank")
  
  random_input_signature_genes <- sample(gene.list, (nrow(dz_genes_up)+nrow(dz_genes_down)))
  
  rand_dz_gene_up <- data.frame(GeneID=random_input_signature_genes[1:nrow(dz_genes_up)])
  rand_dz_gene_down <- data.frame(GeneID=random_input_signature_genes[(nrow(dz_genes_up)+1):length(random_input_signature_genes)])
  random_cmap_scores <- c(random_cmap_scores, cmap_score(rand_dz_gene_up,rand_dz_gene_down,cmap_exp_signature))
}

rand_cmap_scores <- random_cmap_scores 
```
## Compute cmap scores 
```{r}
#clear env as necessary after saving relevant files
cmap_score <- function(sig_up, sig_down, drug_signature) {
	num_genes <- nrow(drug_signature)
	ks_up <- 0
	ks_down <- 0
	connectivity_score <- 0
	
	drug_signature[,"rank"] <- rank(drug_signature[,"rank"])

	# Merge the drug signature with the disease signature by GeneID. This becomes the V(j) from the algorithm description
	up_tags_rank <- merge(drug_signature, sig_up, by.x = "ids", by.y = 1)
	down_tags_rank <- merge(drug_signature, sig_down, by.x = "ids", by.y = 1)

	up_tags_position <- sort(up_tags_rank$rank)
	down_tags_position <- sort(down_tags_rank$rank)

	num_tags_up <- length(up_tags_position)
	num_tags_down <- length(down_tags_position)

	# note that the original writers of this function have used a different operator here than in the previous cmap randoms computation--I'm not sure of the reasons for this, or if it was done in error, but i've chosen to try both and evaluate which seems most accurate.
	if(num_tags_up > 1 || num_tags_down > 1) {
		a_up <- 0
		b_up <- 0
				
		a_up <- max(sapply(1:num_tags_up,function(j) {
			j/num_tags_up - up_tags_position[j]/num_genes
		}))
		b_up <- max(sapply(1:num_tags_up,function(j) {
			up_tags_position[j]/num_genes - (j-1)/num_tags_up
		}))
		
		if(a_up > b_up) {
			ks_up <- a_up
		} else {
			ks_up <- -b_up
		}

		a_down <- 0
		b_down <- 0

		a_down <- max(sapply(1:num_tags_down,function(j) {
			j/num_tags_down - down_tags_position[j]/num_genes
		}))
		b_down <- max(sapply(1:num_tags_down,function(j) {
			down_tags_position[j]/num_genes - (j-1)/num_tags_down
		}))
		
		if(a_down > b_down) {
			ks_down <- a_down
		} else {
			ks_down <- -b_down
		}
		
		if (sum(sign(c(ks_down,ks_up))) == 0) {
			connectivity_score <- ks_up - ks_down # different signs
		}
	}
	return(connectivity_score)
}


dz_cmap_scores <- NULL
count <- 0
for (exp_id in sig.ids) {
  count <- count + 1
  #print(count)
  #print(paste("Computing score for disease against cmap_experiment_id =",exp_id))
  cmap_exp_signature <- data.frame(gene.list,  rank(-1 * lincs_signatures[, as.character(exp_id)], ties.method="random"))
  colnames(cmap_exp_signature) <- c("ids","rank")
  dz_cmap_scores <- c(dz_cmap_scores, cmap_score(dz_genes_up,dz_genes_down,cmap_exp_signature))
}


# Compute the significance
random_scores <- unlist(rand_cmap_scores)
# Frequency-based p-value using absolute scores from sampling distribution to approximate two-tailed p-value
p_values <- sapply(dz_cmap_scores,function(score) {
	length(which(abs(random_scores) >= abs(score))) / length(random_scores)
})
#compare BH FDR adj. vs q -val
adjusted_p_values <- p.adjust(p_values, method = "BH") #more control over FDR, more similar to iLINCS for downstream comparison
q_values <- qvalue(p_values)$qvalues #nuanced insight into data


drugs <- data.frame(exp_id = sig.ids, cmap_score = dz_cmap_scores, orig.pValue = p_values, pValue = adjusted_p_values)
results = list(drugs, dz_signature)
```

#Validate Hits
```{r}
names(drugs)<-c("id","ConcordanceX","orig.pValue","pValueX")
LINCS <- bind_cols(drugs,lincs_sig_info)
#identical(LINCS[['id...1']],LINCS[['id...5']])
LINCS <- LINCS[ -c(1, 6,12, 15) ]
LINCS <- subset(LINCS, !is.na(ConcordanceX) & pValueX < 0.05 & abs(ConcordanceX) > 0 & abs(ConcordanceX) != Inf)
LINCS <- LINCS[order(LINCS$ConcordanceX),]
LINCS <- LINCS[!duplicated(LINCS$id...5),]
LINCS <- LINCS[!duplicated(LINCS$Perturbagen_ID),]
LINCS <- LINCS[ -c(2,5,8) ]
#calculations force connectivity to (-1,1) range, but reversal/concordance may not be optimal, virtually no concordance values around 0 (we would expect most scores to be around 0)

names(LINCS)[3] <- "Signature ID"
LINCS$Time <- paste(LINCS$Time, "h",sep="")
LINCS$Concentration <- paste(LINCS$Concentration, "uM",sep="")



#download and match signature info/metadata: https://www.ilincs.org/ilincs/signatures/search/
#submit signature to compare results:
#https://www.ilincs.org/ilincs/signatures/main/upload
#validate best perturbagens reversing chosen RD signature input
LINCS<-merge(LINCS, iLINCSoutput, by.x='Perturbagen', by.y='Perturbagen') 
#Supplementary table 8
#filter out duplicates, positive scores. Inspect resulting top hits and annotate with relevant pathways/targets, and then subset to top 50
```
